### ISSUE TITLE
Add support for Climate React / smartmode

### ISSUE THREAD

**Issue by Ivan-L** [andrey-git/pysensibo#2]
The Sensibo API supports enabling/disabling Climate React, internally known as `smartmode`.
The API endpoint specification is here:
https://sensibo.github.io/#/paths/~1pods~1{device_id}~1smartmode/put

It would be great if this command were added to pysensibo and Home Assistant. This would open the door for us to be able to automate the enabling / disabling of Climate React in Home Assistant. For example, Climate React should be enabled in the toddler's room whilst he/she is sleeping there and hence the AC should maintain the desired temperature range in the room whilst the toddler is there, however if the toddler is not sleeping in the room, Climate React should be disabled so that the AC is not turned on/off unnecessarily to maintain the temperature in an empty room.

**Comment by gjohansson-ST** [comment]
This has been added along the way and will be implemented in HA as things move in.
