### ISSUE TITLE
No logging of Current humidity, Sensibo Sky.

### ISSUE THREAD

**Issue by PowerBat80** [andrey-git/pysensibo#81]
# Problem/Motivation
Current humidity seems not to be history/statistics logged?
I have two skyv2 by Sensibo
Firmware: SKY30047
Hardware: esp8266ex 

> (Why the issue was filed)
Current temp, target temp and heat has history/statistics logging but not humidity? 
Then I also can't add only for example current temp to a History graph Card configuration, always all 3 values from the Entity is shown. 

## Expected behavior
Also humidity should be able to see a history/statistics log curve.
Possibility to add only one of the 4 different values to History graph Card, not all. They are not sensors. 

## Proposed changes
Also humidity should be able to see a history/statistics log curve.
Possibility to add any of the 4 different values (sensors) to History graph Card, not all.

The integration is otherways perfect 🥇

**Comment by gjohansson-ST** [comment]
I am partially confused. Are you talking about statistics in Home Assistant I think this should close and open a new issue in the https://github.com/home-assistant/core repository. Thanks

**Comment by PowerBat80** [comment]
Yes, in Home Assistant.
Sorry for post in wrong forum, I will make a new try :)
Case closed here
Br

**Comment by PowerBat80** [comment]
Closed
